### ISSUE TITLE
Validate UUID RFC 4122 using Python's uuid library suggestion

### ISSUE THREAD

**Issue by flojdek** [neoauth/smart-contract#12]
Thanks for a very neat example of a NEO smart contract plus very detailed documentation and very well written/documented code. I've noticed one small thing though that could be improved and that is the RFC 4122 UUID format validation. Doing it by hand seems a bit awkward and the code is much longer than actually using Python's uuid library:

```
>>> import uuid
>>> uuid.UUID("ce8c00c2-4fa5-47de-a07e-1061e62955b0")
UUID('ce8c00c2-4fa5-47de-a07e-1061e62955b0')
>>> uuid.UUID("ce8c00c2-4fa5-47de-a07e-1061e62955b") # Last 0 removed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/uuid.py", line 136, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
>>> uuid.UUID("whatever")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/uuid.py", line 136, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
>>>
```
So a bit of code like this would do the trick:
```python
try:
  val = UUID(input)
except ValueError:
  return False
```
What do you think? Not a major suggestion of course ;)

**Comment by revett** [comment]
Thanks for raising this issue @flojdek! Unfortunately, I don't think you can include external dependencies within a NEO smart contract, so this would not be possible.

**Comment by flojdek** [comment]
Hmmm, interesting, I need to look into that more closely. Even if it's part of Python's standard library which `uuid` is? That would be very limiting indeed. I found this example smart contract https://github.com/CityOfZion/neo-python/blob/master/examples/smart-contract.py that uses part of the Python's standard library like `time`.

**Comment by revett** [comment]
I may be mistaken - I'll give it a try this week and report back 👍

**Comment by jeroenptrs** [comment]
Hi @flojdek! Thanks for your suggestion, I've looked into it but the link you shared is not a smart contract example, but a logging implementation using neo-python 😄 As the description says:

```Example of running a NEO node and receiving notifications when events
of a specific smart contract happen.```

That being said, I'm going to close this issue for now. Feel free to reopen it if an implementation surfaces that we can use in the smart contract!
